name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt
      
  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact
          
      - name: Cat file
        run: cat hello.txt
    # Append a new job named - download
    # a. This job should execute after the - build job
    # b. This jobs runs on - ubuntu-latest
    # c. Add step to download the text file from previous job and place it in path: ./artifacts
    # d. Add step to display the content of hello.txt file
    # Use cat ./artifacts/hello.txt command
